//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desmond {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>KF-BurningParis</string>\r\n  <string>KF-Bioticslab</string>\r\n  <string>KF-O" +
            "utpost</string>\r\n  <string>KF-VolterManor</string>\r\n  <string>KF-Catacombs</stri" +
            "ng>\r\n  <string>KF-EvacuationPoint</string>\r\n  <string>KF-Farmhouse</string>\r\n  <" +
            "string>KF-BlackForest</string>\r\n  <string>KF-Prison</string>\r\n  <string>KF-Conta" +
            "inmentStation</string>\r\n  <string>KF-HostileGrounds</string>\r\n  <string>KF-Infer" +
            "nalRealm</string>\r\n  <string>KF-ZedLanding</string>\r\n  <string>KF-Nuked</string>" +
            "\r\n  <string>KF-TheDescent</string>\r\n  <string>KF-TragicKingdom</string>\r\n  <stri" +
            "ng>KF-Nightmare</string>\r\n  <string>KF-KrampusLair</string>\r\n  <string>KF-DieSec" +
            "tor</string>\r\n  <string>KF-PowerCore_Holdout</string>\r\n  <string>KF-Lockdown</st" +
            "ring>\r\n  <string>KF-Airship</string>\r\n  <string>KF-ShoppingSpree</string>\r\n  <st" +
            "ring>KF-MonsterBall</string>\r\n  <string>KF-Santasworkshop</string>\r\n  <string>KF" +
            "-Spillway</string>\r\n  <string>KF-SteamFortress</string>\r\n  <string>KF-AshwoodAsy" +
            "lum</string>\r\n  <string>KF-Sanitarium</string>\r\n  <string>KF-Biolapse</string>\r\n" +
            "  <string>KF-Desolation</string>\r\n  <string>KF-HellmarkStation</string>\r\n  <stri" +
            "ng>KF-Elysium</string>\r\n  <string>KF-Dystopia2029</string>\r\n  <string>KF-Moonbas" +
            "e</string>\r\n  <string>KF-Netherhold</string>\r\n  <string>KF-CarillonHamlet</strin" +
            "g>\r\n  <string>KF-Rig</string>\r\n  <string>KF-BarmwichTown</string>\r\n  <string>KF-" +
            "Crash</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StockMaps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StockMaps"]));
            }
            set {
                this["StockMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WorkshopMaps {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WorkshopMaps"]));
            }
            set {
                this["WorkshopMaps"] = value;
            }
        }
    }
}
